/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testrunnable;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FormThucThi extends javax.swing.JFrame {
    ArrayList<String> dsChuoi;
    /**
     * Creates new form FormThucThi
     */
    XuLy tsr = new XuLy();
    
    public static LinkedList<ArrayList<String>> DNAS_motifs;

    public static LinkedList<ArrayList<String>> getDNAS_motifs() {
        return DNAS_motifs;
    }

    public static String thongbao;

    public static void setThongbao(String thongbao) {
        FormThucThi.thongbao = thongbao;
    }
    
    public static void setDNAS_motifs(LinkedList<ArrayList<String>> DNAS_motifs) {
        FormThucThi.DNAS_motifs = DNAS_motifs;
    }
    
    public FormThucThi() {
        initComponents();
        txtTimeSongSong.enable(false);
        txtTimeTuanTu.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGhiFile = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();
        txtChuoiTim = new javax.swing.JTextField();
        txtSoDotBien = new javax.swing.JTextField();
        txtTimeTuanTu = new javax.swing.JTextField();
        lblTuanTu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaFile = new javax.swing.JTextArea();
        lblSongSong = new javax.swing.JLabel();
        txtTimeSongSong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaKetQua = new javax.swing.JTextArea();
        btnThucThiSongSong = new javax.swing.JButton();
        btnThucThiTuanTu1 = new javax.swing.JButton();
        lblNhapChuoiMuonTim = new javax.swing.JLabel();
        lblNhapSoDotBien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGhiFile.setText("Ghi file");

        btnDocFile.setText("Ä�á»�c file");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        lblTuanTu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTuanTu.setForeground(new java.awt.Color(255, 51, 51));
        lblTuanTu.setText("Tuáº§n tá»±");

        txtAreaFile.setColumns(20);
        txtAreaFile.setRows(5);
        jScrollPane1.setViewportView(txtAreaFile);

        lblSongSong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSongSong.setForeground(new java.awt.Color(255, 51, 51));
        lblSongSong.setText("Song song");

        txtAreaKetQua.setColumns(20);
        txtAreaKetQua.setRows(5);
        jScrollPane2.setViewportView(txtAreaKetQua);

        btnThucThiSongSong.setText("Thá»±c thi");
        btnThucThiSongSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucThiSongSongActionPerformed(evt);
            }
        });

        btnThucThiTuanTu1.setText("Thá»±c thi");
        btnThucThiTuanTu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucThiTuanTu1ActionPerformed(evt);
            }
        });

        lblNhapChuoiMuonTim.setText("Nháº­p vÃ o chuá»—i muá»‘n tÃ¬m");

        lblNhapSoDotBien.setText("Nháº­p sá»‘ Ä‘á»™t biáº¿n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnGhiFile)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtChuoiTim, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNhapChuoiMuonTim))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSoDotBien, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNhapSoDotBien)))
                        .addContainerGap(170, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTuanTu)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnThucThiTuanTu1))
                                    .addComponent(txtTimeTuanTu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSongSong)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThucThiSongSong))
                                    .addComponent(txtTimeSongSong, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(77, 77, 77))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(btnDocFile)
                    .addContainerGap(773, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnGhiFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChuoiTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNhapChuoiMuonTim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDotBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNhapSoDotBien))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTuanTu)
                                    .addComponent(btnThucThiTuanTu1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimeTuanTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSongSong)
                                    .addComponent(btnThucThiSongSong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimeSongSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(btnDocFile)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:        
        txtAreaFile.setText("");
        dsChuoi = tsr.docFile("C:\\Users\\Nhan\\Desktop\\DoAn_XuLyTinhToanSongSong\\File\\chuoitest2.txt");
        for(String s: dsChuoi)
        {
            try
            {
                int a = Integer.parseInt(s);
            }
            catch(Exception ex)
            {
                txtAreaFile.setText(txtAreaFile.getText() + s + "\n");
            }                    
            
        }
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnThucThiTuanTu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucThiTuanTu1ActionPerformed
        // TODO add your handling code here:
        txtAreaKetQua.setText("");
        try
        {
        String a = txtChuoiTim.getText();
        int b = Integer.parseInt(txtSoDotBien.getText());
        long startTime = System.currentTimeMillis();
        tsr.thucThiTT(a,b);
        long endTime = System.currentTimeMillis(); 
        txtTimeTuanTu.setText("Thá»�i gian thá»±c thi: " + (endTime - startTime)/1000F);
        if(DNAS_motifs.isEmpty())
        {
            txtAreaKetQua.setText("TÃ¬m khÃ´ng thÃ nh cÃ´ng");
        }
        else
        {
            txtAreaKetQua.setText(thongbao);

        }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex.toString(),"Lá»—i",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThucThiTuanTu1ActionPerformed

    private void btnThucThiSongSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucThiSongSongActionPerformed
        // TODO add your handling code here:
        try {
            String a = txtChuoiTim.getText();
            int b = Integer.parseInt(txtSoDotBien.getText());
            long start_time2 = System.currentTimeMillis();
            XuLy.thucThiSS(a, b, 6);
            long end_time2 = System.currentTimeMillis();
            txtTimeSongSong.setText("Thá»�i gian thá»±c thi: " + (end_time2 - start_time2)/1000F);
            String output = "";
            String t = txtAreaKetQua.getText();
            for(int i =0;i<DNAS_motifs.size();i++)
            {
            	output = "Tìm được chuỗi thích hợp trong chuỗi " + (i+1) + " :";
                for(int j=0;j<DNAS_motifs.get(i).size();j++)
                {
                    try {
                        int mes = Integer.parseInt(DNAS_motifs.get(i).get(j));
                        if(mes == 0)
                        {
                            output ="Không tìm được chuỗi thích hợp trong chuỗi " + (i+1) +"\n";
                        }
                        else
                        {
                            output ="Tìm được chuỗi thích hợp trong chuỗi " + (i+1) +"\n";
                        }
                    } 
                    catch (Exception e) 
                    {
                        output += DNAS_motifs.get(i).get(j) + "\t";
                    }
                }
                output += "\n";
                t += output;
                txtAreaKetQua.setText(t);
            }
        } catch (Exception e) {
        	e.getStackTrace();
        	System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnThucThiSongSongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThucThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThucThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThucThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThucThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThucThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnThucThiSongSong;
    private javax.swing.JButton btnThucThiTuanTu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNhapChuoiMuonTim;
    private javax.swing.JLabel lblNhapSoDotBien;
    private javax.swing.JLabel lblSongSong;
    private javax.swing.JLabel lblTuanTu;
    private javax.swing.JTextArea txtAreaFile;
    private javax.swing.JTextArea txtAreaKetQua;
    private javax.swing.JTextField txtChuoiTim;
    private javax.swing.JTextField txtSoDotBien;
    private javax.swing.JTextField txtTimeSongSong;
    private javax.swing.JTextField txtTimeTuanTu;
    // End of variables declaration//GEN-END:variables
}
